import React from 'react'

export const cars = [
  {
    id: 1,
    carname: 'BMW X5 series',
    cost: '24',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car1.jpg',
    date: '25-August-2023',
    status: 'Active',
  },
  {
    id: 2,
    carname: 'Toyota Corolla',
    cost: '45',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car2.jpg',
    date: '5-August-2023',
    status: 'Closed',
  },
  {
    id: 3,
    carname: 'Volks wagen',
    cost: '43',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car3.jpg',
    date: '25-May-2023',
    status: 'Active',
  },
  {
    id: 4,
    carname: 'Nissan Flat booth',
    cost: '224',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car4.jpg',
    date: '25-june-2023',
    status: 'Active',
  },
  {
    id: 5,
    carname: 'Golf Jeep',
    cost: '32',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car5.jpg',
    date: '25-April-2023',
    status: 'Closed',
  },
  {
    id: 6,
    carname: 'Mazda',
    cost: '14',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car6.jpg',
    date: '2-August-2023',
    status: 'Active',
  },
  {
    id: 7,
    carname: 'Bently',
    cost: '34',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car7.jpg',
    date: '25-August-2023',
    status: 'Active',
  },
  {
    id: 8,
    carname: 'Jeep',
    cost: '24',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car8.jpg',
    date: '25-November-2023',
    status: 'Closed',
  },
  {
    id: 9,
    carname: 'Rolls Royce',
    cost: '124',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car9.jpg',
    date: '1-August-2023',
    status: 'Closed',
  },
  {
    id: 10,
    carname: 'Honda',
    cost: '24',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car10.jpg',
    date: '25-August-2023',
    status: 'Closed',
  },
]

export const transactionhistory = [
  {
    id: 1,
    type: 'incoming',
    amount: '400',
    description: `Withdrawal to personal Account`,
    date: '20 September,2023',
    status: 'Successfull',
  },
  {
    id: 2,
    type: 'incoming',
    amount: '240',
    description: `BMW X5 series Lease payment`,
    date: '15 September,2023',
    status: 'Successfull',
  },
  {
    id: 3,
    type: 'outgoing',
    amount: '100',
    description: `Withdrawal to personal Account`,
    date: '5 September,2023',
    status: 'Pending',
  },
  {
    id: 4,
    type: 'incoming',
    amount: '200',
    description: `Cash Reversal for withdrawals made`,
    date: '1 September,2023',
    status: 'Successfull',
  },
  {
    id: 5,
    type: 'outgoing',
    amount: '200',
    description: `Withdrawal to personal Account`,
    date: '25 August,2023',
    status: 'Failed',
  },
]

export const leasehistory = [
  {
    id: 1,
    carname: 'BMX Series ',
    amount: '210',
    renter: `Olamide Oluwalet`,
    date: '20 September,2023',
    status: 'Successfull',
  },
  {
    id: 2,
    carname: 'BMX Series ',
    amount: '110',
    renter: `Ibrahim Isaac`,
    date: '10 September,2023',
    status: 'canceled',
  },
  {
    id: 3,
    carname: 'Honda Civie ',
    amount: '210',
    renter: `Micheal Scofield`,
    date: '8 September,2023',
    status: 'Successfull',
  },
  {
    id: 4,
    carname: 'BMX Series ',
    amount: '300',
    renter: `Okwu Chiedozie`,
    date: '6 September,2023',
    status: 'Pending',
  },
  {
    id: 5,
    carname: 'BMX Series ',
    amount: '150',
    renter: `Miriam Ezeobi`,
    date: '2 September,2023',
    status: 'Canceled',
  },
]
