import React from 'react'

export const Testimonies = [
  {
    id: 1,
    carname: 'BMW X5 series',
    cost: '24',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car1.jpeg',
    date: '25-August-2023',
    status: 'active',
  },
  {
    id: 2,
    carname: 'Toyota Corolla',
    cost: '45',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car2.jpeg',
    date: '5-August-2023',
    status: 'closed',
  },
  {
    id: 3,
    carname: 'Volks wagen',
    cost: '43',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car3.jpeg',
    date: '25-May-2023',
    status: 'active',
  },
  {
    id: 4,
    carname: 'Nissan Flat booth',
    cost: '224',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car4.jpeg',
    date: '25-june-2023',
    status: 'active',
  },
  {
    id: 5,
    carname: 'Golf Jeep',
    cost: '32',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car5.jpeg',
    date: '25-April-2023',
    status: 'closed',
  },
  {
    id: 6,
    carname: 'Mazda',
    cost: '14',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car6.jpeg',
    date: '2-August-2023',
    status: 'active',
  },
  {
    id: 7,
    carname: 'Bently',
    cost: '34',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car7.jpeg',
    date: '25-August-2023',
    status: 'active',
  },
  {
    id: 8,
    carname: 'Jeep',
    cost: '24',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car8.jpeg',
    date: '25-November-2023',
    status: 'closed',
  },
  {
    id: 9,
    carname: 'Rolls Royce',
    cost: '124',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car9.jpeg',
    date: '1-August-2023',
    status: 'closed',
  },
  {
    id: 10,
    carname: 'Honda',
    cost: '24',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga recusandae ipsa deleniti laboriosam beatae illum dolorem earum, maiores quis sit!`,
    image: '/images/car10.jpeg',
    date: '25-August-2023',
    status: 'closed',
  },
]
